<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-FR5NQIN" failures="2" tests="8" name="LoginTest" time="7.908" errors="0" timestamp="23 Nov 2018 18:14:03 GMT">
  <testcase classname="Railway.LoginTest" name="TC01" time="0.444"/>
  <testcase classname="Railway.LoginTest" name="TC02" time="0.306"/>
  <testcase classname="Railway.LoginTest" name="TC03" time="0.315">
    <failure type="java.lang.AssertionError" message="expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at Railway.LoginTest.TC03(LoginTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC03 -->
  <testcase classname="Railway.LoginTest" name="TC04" time="0.107"/>
  <testcase classname="Railway.LoginTest" name="TC05" time="1.009">
    <failure type="java.lang.AssertionError" message="expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at Railway.LoginTest.TC05(LoginTest.java:51)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC05 -->
  <testcase classname="Railway.LoginTest" name="TC06" time="0.585"/>
  <testcase classname="Railway.LoginTest" name="TC08" time="0.294"/>
  <testcase classname="Railway.LoginTest" name="TC09" time="0.743"/>
</testsuite> <!-- LoginTest -->
