<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-FR5NQIN" failures="2" tests="7" name="Login" time="10.991" errors="0" timestamp="29 Nov 2018 15:31:08 GMT">
  <testcase classname="Railway.LoginTest" name="TC01" time="0.484"/>
  <testcase classname="Railway.LoginTest" name="TC02" time="0.359"/>
  <testcase classname="Railway.LoginTest" name="TC03" time="0.441">
    <failure type="java.lang.AssertionError" message="expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at Railway.LoginTest.TC03(LoginTest.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC03 -->
  <testcase classname="Railway.LoginTest" name="TC04" time="0.149"/>
  <testcase classname="Railway.LoginTest" name="TC05" time="1.425">
    <failure type="java.lang.AssertionError" message="expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]">
      <![CDATA[java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at Railway.LoginTest.TC05(LoginTest.java:51)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- TC05 -->
  <testcase classname="Railway.LoginTest" name="TC06" time="0.77"/>
  <testcase classname="Railway.LoginTest" name="TC08" time="0.383"/>
</testsuite> <!-- Login -->
